baseURL = 'https://grace-punzalan.github.io/'
languageCode = 'en-us'
title = 'My Hugo Site'

[params]
  description = "Test Only."


[permalinks]
  blog = "/blog/:filename/"
  news = "/news/:filename/"